packages:
  - apps/*
  - packages/*

catalog:
  drizzle-orm: 0.41.0
  pg: 8.16.0
  discord-api-types: 0.37.120

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@heroui/shared-utils'
  - esbuild
  - sharp
