packages:
  - apps/*
  - packages/*

catalog:
  drizzle-orm: ^0.41.0
  pg: ^8.14.1
  discord.js: ^14.19.3

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@heroui/shared-utils'
  - esbuild
  - sharp
