name: 機能の改善
description: 既存機能の改善に関するissueを作成します。
assignees:
  - nonick-mc
labels:
  - improvement
body:
  - type: checkboxes
    attributes:
      label: 影響するプロダクト
      description: 機能の改善によって変更を加える必要のあるプロダクトはどれですか？
      options:
        - label: bot
          required: false
        - label: dashboard
          required: false
        - label: docs
          required: false
  - type: textarea
    attributes:
      label: 機能に関する説明
      description: 改善する機能の内容について説明してください。
    validations:
      required: true
