name: Deploy Docs to GitHub Pages

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types: 
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install

      - name: Build Nextra site
        run: pnpm build:web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
